name: My First Workfloow
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run: echo "Welcome My First Github Actions"
    - name: List File
      run: ls
    - name: Read Files
      run: cat README.md
